server:
  port: 7021

spring:
  application:
    name: application-sleuthservice

eureka:
  instance:
    instance-id: application-serviceA-A2-7021
  client:
    service-url:
      defaultZone: http://172.26.125.114:7001/eureka,http://172.26.125.115:7001/eureka,http://172.26.125.118:7001/eureka

#日志输出，指明日志存放位置；同时需要在资源路径下引入配置文件
logging:
  file: logs/application-idleGoodService-${server.port}.logs

#actuator的配置
management:
  port: 7121
  security:
    enabled: false